# Configure how data is stored here.
database:

  # What database should be used?
  # Valid types: 'SQLite', 'MySQL'
  # Expected: [String], Default: ['SQLite']
  database-type: 'SQLite'

  #TODO REMOVE
  # Table to use in the database
  # Expected: [String], Default: ['phantomeconomy']
  table: 'phantomeconomy'

  #TODO IMPLEMENT
  # In this section, you can change the table names for each account.
  # Using MySQL and want to sync account balances over each server? Check this link:
  # https://github.com/lokka30/PhantomEconomy/wiki/%5Bv2%5D-Sharing-account-data-across-servers
  account-tables:
    playerAccount: 'phantomeconomy_global'
    nonPlayerAccount: 'phantomeconomy_global'
    bankAccount: 'phantomeconomy_global'

  # If you have used 'MySQL' above, then these settings will be used to connect to manage data.
  mysql-settings:

    # Expected: [String], Default: ['localhost']
    host: 'localhost'

    # Expected: [Integer], Default: [3306]
    port: 3306

    # Expected: [String], Default: ['root']
    username: 'root'

    # Expected: [String], Default: ['password123']
    password: 'password123'

    # Expected: [String], Default: ['minecraft']
    database: 'minecraft'

    # Expected: [String], Default: ['true']
    # Warning: Remember to keep this as a String, not a Boolean!
    ssl: 'true'


# You can customise each currency here.
currencies:

  # This is the list of currencies which can be used on the server.
  # Warning: Make sure you include a currency here!
  # Expected: [List<String>], Default: ['dollars']
  enabled-currencies:
    - 'dollars'

  # When users are using /pay, /baltop, etc, and don't specify a specific currency to use, what will be used by default?
  # Expected: [String], Default: ['dollars']
  default-currency: 'dollars'

  # If you are using Vault, you must specify a currency to use.
  # Warning: If plugins are using Vault and you haven't set a valid currency, serious issues could occur with other plugins!
  # Expected: [String], Default: ['dollars']
  vault-currency: 'dollars'

  # Here you can edit all of the enabled currencies.
  # Warning: Make sure you put your currency in 'enabled-currencies' once you have made it!
  # Warning: You shouldn't rename currencies! People's balances will not transfer, their balances will stick with the currency name previous to when it was changed.
  currency-settings:

    # The default currency.
    dollars:

      # Users will be given this amount of money when they use the currency for the first time
      # e.g. give $50 to players so they can get started
      # Expected: [Double], Default: [50.00]
      default-balance: 50.00

      formatting:

        # This is the format used to trim decimals off of various numbers, such as the player's balance or how much money a user was given.
        # e.g. trimming decimals - 2.22222 -> 2.22
        # Expected: [String], Default: ['0.00']
        decimal-format: '0.00'

        # The format when displaying as a human-readable balance.
        # You can include %word% and it will add the singular/plural word customised below.
        # e.g. '$%balance% %word%' = '$5 dollars' or '$1 dollar'
        # e.g. '$%balance%' = '$5' or '$1'
        # e.g. '%balance% %word' = '5 dollars' or '1 dollar'
        # Expected: [String], Default: ['$%balance']
        final-format: '$%balance%'

        # You can edit the words placeholder here if you are using it in the format above.
        words:

          # When the balance is $1, e.g. 1 dollar
          # Expected: [String], Default: ['dollar']
          singular: 'dollar'

          # When the balance is not $1, e.g. 5 dollars
          # Expected: [String], Default: ['dollars']
          plural: 'dollars'

    # An example 'coins' currency. You can delete it if you want. It is disabled by default as it is not added to the 'enabled-currencies' list.
    coins:
      default-balance: 10.50
      formatting:
        storage-rounding: 2
        decimal-readable-format: '0.00'
        final-readable-format: '%balance% %word%'
        words:
          singular: 'coin'
          plural: 'coins'

# Here you can manage what tasks will start and repeat. Having these enabled will make the plugin use less memory but might increase the rate of which the plugin needs to use the database.
# IMPORTANT: Changes in this section will only take effect on a server restart.
startup-tasks:

  # Clear the Baltop cache?
  # This is highly recommended, else the baltop list will only update every restart.
  # When the baltop cache is cleared, it will fetch new results from the database.
  # Rate: 15 minutes
  clear-baltop-cache: true

  # Clear the PlayerAccount balance cache?
  # This isn't really required as players are removed from the cache when they leave the server.
  # Rate: 45 minutes
  clear-player-account-cache: false

  # Clear the NonPlayerAccount cache?
  # This should be enabled as this cache is only reset when the server stops.
  # Rate: 45 minutes
  clear-non-player-account-cache: true

  # Clear the BankAccount cache?
  # This should be enabled as this cache is only reset when the server stops.
  # Rate: 45 minutes
  clear-bank-account-cache: true

# Other options not related to the economy
other-options:

  # Should PE check for updates on startup?
  # Disable if you check your Spigot alerts regularly.
  # Expected: [Boolean], Default: [true]
  use-update-checker: true

  # Only change this if you know what you are doing!
  # It is recommended to backup your old settings.yml file and edit a newly generated one instead.
  # Expected: [Integer]
  file-version: 6